---
version: "2.1"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Paris
    volumes:
      - ./sonarr:/config
      - ./sonarr/downloads:/downloads
      - ./sonarr/tv:/tv
    ports:
      - 8989:8989
    network_mode: host
    restart: unless-stopped
